apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-atm-ingress
spec:
  rules:
  - host: smartatm.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smart-atm-service
            port:
              number: 80